In [1]:
# Install convokit and import dataset and pandas

!pip install convokit
import pandas as pd

from convokit import Corpus, download
corpus = Corpus(filename=download("persuasionforgood-corpus"))
corpus.print_summary_stats()

Collecting convokit
  Downloading convokit-4.1.0.tar.gz (240 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 240.9/240.9 kB 5.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: matplotlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.10.0)
Requirement already satisfied: scipy>1.14 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.16.3)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.2.2)
Requirement already satisfied: numpy>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.0.2)
Collecting msgpack-numpy>=0.4.3.2 (from convokit)
  Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl.metadata (5.0 kB)
Requirement already satisfied: spacy>=3.8.2 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.8.14)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.6.1)
Requirement already satisfied: nltk>=3.4 in /usr/local/lib/python3.12/dist-packages (from convokit) (3.9.1)
Requirement already satisfied: dill>=0.2.9 in /usr/local/lib/python3.12/dist-packages (from convokit) (0.3.8)
Requirement already satisfied: joblib>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from convokit) (1.5.3)
Collecting clean-text>=0.6.0 (from convokit)
  Downloading clean_text-0.7.1-py3-none-any.whl.metadata (9.1 kB)
Collecting unidecode>=1.1.1 (from convokit)
  Downloading Unidecode-1.4.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (4.67.3)
Collecting pymongo>=4.0 (from convokit)
  Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (10.0 kB)
Requirement already satisfied: pyyaml>=5.4.1 in /usr/local/lib/python3.12/dist-packages (from convokit) (6.0.3)
Collecting dnspython>=1.16.0 (from convokit)
  Downloading dnspython-2.8.0-py3-none-any.whl.metadata (5.7 kB)
Requirement already satisfied: thinc<8.4.0,>=8.3.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (8.3.13)
Collecting h5py==3.12.1 (from convokit)
  Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.5 kB)
Requirement already satisfied: numexpr>=2.8.0 in /usr/local/lib/python3.12/dist-packages (from convokit) (2.14.1)
Requirement already satisfied: ruff>=0.4.8 in /usr/local/lib/python3.12/dist-packages (from convokit) (0.15.10)
Requirement already satisfied: bottleneck in /usr/local/lib/python3.12/dist-packages (from convokit) (1.4.2)
Collecting evaluate (from convokit)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (from convokit) (5.4.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from convokit) (4.0.0)
Collecting emoji>=2.1.0 (from clean-text>=0.6.0->convokit)
  Downloading emoji-2.15.0-py3-none-any.whl.metadata (5.7 kB)
Collecting ftfy<7.0,>=6.0 (from clean-text>=0.6.0->convokit)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib>=3.0.0->convokit) (2.9.0.post0)
Requirement already satisfied: msgpack>=0.5.2 in /usr/local/lib/python3.12/dist-packages (from msgpack-numpy>=0.4.3.2->convokit) (1.1.2)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4->convokit) (8.3.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.4->convokit) (2025.11.3)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->convokit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.0->convokit) (2026.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->convokit) (3.6.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.0.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (0.24.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.32.4)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy>=3.8.2->convokit) (75.2.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.0->convokit) (1.3.3)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (3.25.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (18.1.0)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets->convokit) (1.10.1)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (5.0.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (2.10.0+cpu)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers->convokit) (4.15.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (3.13.5)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from ftfy<7.0,>=6.0->clean-text>=0.6.0->convokit) (0.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->convokit) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets->convokit) (0.28.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.8.2->convokit) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.8.2->convokit) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.0.0->spacy>=3.8.2->convokit) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->convokit) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy>=3.8.2->convokit) (2026.2.25)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->convokit) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers->convokit) (3.6.1)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->convokit) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->convokit) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers->convokit) (0.7.0)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (0.0.4)
Requirement already satisfied: cloudpathlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.8.2->convokit) (0.23.0)
Requirement already satisfied: smart-open>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<2.0.0,>=1.0.0->spacy>=3.8.2->convokit) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy>=3.8.2->convokit) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->convokit) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets->convokit) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (2.20.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy>=3.8.2->convokit) (2.1.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers->convokit) (1.3.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy>=3.8.2->convokit) (0.1.2)
Downloading h5py-3.12.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 77.0 MB/s eta 0:00:00
Downloading clean_text-0.7.1-py3-none-any.whl (15 kB)
Downloading dnspython-2.8.0-py3-none-any.whl (331 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 331.1/331.1 kB 24.8 MB/s eta 0:00:00
Downloading msgpack_numpy-0.4.8-py2.py3-none-any.whl (6.9 kB)
Downloading pymongo-4.16.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 86.2 MB/s eta 0:00:00
Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 235.8/235.8 kB 20.7 MB/s eta 0:00:00
Downloading evaluate-0.4.6-py3-none-any.whl (84 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 8.6 MB/s eta 0:00:00
Downloading emoji-2.15.0-py3-none-any.whl (608 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 608.4/608.4 kB 41.6 MB/s eta 0:00:00
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.8/44.8 kB 3.3 MB/s eta 0:00:00
Building wheels for collected packages: convokit
  Building wheel for convokit (pyproject.toml) ... done
  Created wheel for convokit: filename=convokit-4.1.0-py3-none-any.whl size=292185 sha256=5e26677e6f918d7fb66afba79a00e14d49049755c468df075f86c7af51f57760
  Stored in directory: /root/.cache/pip/wheels/5e/d8/32/b867fe29313972bfba4cb57051565bd1395d7561df03839b5e
Successfully built convokit
Installing collected packages: unidecode, msgpack-numpy, h5py, ftfy, emoji, dnspython, pymongo, clean-text, evaluate, convokit
  Attempting uninstall: h5py
    Found existing installation: h5py 3.16.0
    Uninstalling h5py-3.16.0:
      Successfully uninstalled h5py-3.16.0
Successfully installed clean-text-0.7.1 convokit-4.1.0 dnspython-2.8.0 emoji-2.15.0 evaluate-0.4.6 ftfy-6.3.1 h5py-3.12.1 msgpack-numpy-0.4.8 pymongo-4.16.0 unidecode-1.4.0
No configuration file found at /root/.convokit/config.yml; writing with contents:
# Default Backend Parameters
db_host: localhost:27017
data_directory: ~/.convokit/saved-corpora
model_directory: ~/.convokit/saved-models
default_backend: mem
Downloading persuasionforgood-corpus to /root/.convokit/saved-corpora/persuasionforgood-corpus
Downloading persuasionforgood-corpus from http://zissou.infosci.cornell.edu/convokit/datasets/persuasionforgood-corpus/persuasionforgood.zip (2.7MB)... Done
Number of Speakers: 1285
Number of Utterances: 20932
Number of Conversations: 1017

In [2]:
# Creating dataframe so I can download a CSV of the dataset to use in Jamovi. Collecting the metadata.
rows = []

for conversation in corpus.iter_conversations():
    rows.append({
        "dialogue_id":  conversation.meta.get("dialogue_id", None),
        "persuader_id": conversation.meta.get("user_er", None),
        "persuadee_id": conversation.meta.get("user_ee", None),
        "donation_ee":  conversation.meta.get("donation_ee", None),
        "donation_er":  conversation.meta.get("donation_er", None),
        "is_annotated": conversation.meta.get("is_annotated", None),
    })

df_convos = pd.DataFrame(rows)
print(df_convos.shape)
df_convos.head()

(1017, 6)

,dialogue_id,persuader_id,persuadee_id,donation_ee,donation_er,is_annotated
0,20180904-045349_715_live,A3A07QA5U733HQ,A25L985XCNESXE,0.00,0.00,True
1,20180904-154250_98_live,A3GGA28ZY5CYTH,AG3ISFZMFGDQ9,2.00,0.00,False
2,20180904-024226_703_live,A22WWSTT8TU7G1,A2JQOU78XJA6VP,0.05,0.05,True
3,20180904-100019_870_live,A29NICQTS9B05U,A302K8B1H9ISJA,0.00,0.00,False
4,20180904-001208_706_live,A3LQ2F30FKC0CZ,A1RGD548VIVY96,1.00,0.00,False

In [3]:
# getting persuader information. creating new dataframe
rows = []

for speaker in corpus.iter_speakers():
    rows.append({
        "persuader_id":  speaker.id,
        # Big Five Personality Traits
        "extrovert":     speaker.meta.get("extrovert", None),
        "agreeable":     speaker.meta.get("agreeable", None),
        "conscientious": speaker.meta.get("conscientious", None),
        "neurotic":      speaker.meta.get("neurotic", None),
        "open":          speaker.meta.get("open", None),
        # Demographics
        "age":           speaker.meta.get("age", None),
        "sex":           speaker.meta.get("sex", None),
        "race":          speaker.meta.get("race", None),
        "marital":       speaker.meta.get("marital", None),
        "employment":    speaker.meta.get("employment", None),
        "income":        speaker.meta.get("income", None),
        "edu":           speaker.meta.get("edu", None),
        "religion":      speaker.meta.get("religion", None),
        "ideology":      speaker.meta.get("ideology", None),
    })

df_speakers = pd.DataFrame(rows)
print(df_speakers.shape)
df_speakers.head()

(1285, 15)

,persuader_id,extrovert,agreeable,conscientious,neurotic,open,age,sex,race,marital,employment,income,edu,religion,ideology
0,A3A07QA5U733HQ,3.2,3.2,3.6,1.6,3.6,34.0,Male,White,Unmarried,Employed for wages,5.0,Less than four-year college,Other religion,Liberal
1,A25L985XCNESXE,3.2,4.0,3.8,2.0,3.2,50.0,Female,White,Married,Employed for wages,10.0,Less than four-year college,Protestant,Conservative
2,A3GGA28ZY5CYTH,3.6,3.8,4.0,4.0,3.6,25.0,Female,White,Married,Other,6.0,Four-year college,Atheist,Moderate
3,AG3ISFZMFGDQ9,3.0,3.6,3.2,3.0,3.0,30.0,Male,White,Unmarried,Employed for wages,2.0,Less than four-year college,Atheist,Liberal
4,A22WWSTT8TU7G1,1.0,5.0,2.8,1.0,4.6,36.0,Female,White,Unmarried,Employed for wages,1.0,Less than four-year college,Catholic,Moderate

In [4]:
#Merging dataframes of persuader ID and information
df_merged = pd.merge(df_convos, df_speakers, on="persuader_id", how="left")

#defining which are numerical columns and categorical columns
numeric_cols = ["donation_ee", "donation_er", "extrovert", "agreeable",
                "conscientious", "neurotic", "open", "age", "income"]

categorical_cols = ["sex", "race", "marital", "employment", "edu", "religion", "ideology"]

#Average the numeric columns per persuader - making sure the same participants is not counted as two people which could skew results.
df_numeric = df_merged.groupby("persuader_id")[numeric_cols].mean().reset_index()

#use first value in categorical columns
df_categorical = df_merged.groupby("persuader_id")[categorical_cols].first().reset_index()

#use persuader ID as the axis to merge everything back together
df_persuaders = pd.merge(df_numeric, df_categorical, on="persuader_id")

#create final dataframe
print(df_persuaders.shape)
print(df_persuaders.columns.tolist())
df_persuaders.head()

(701, 17)
['persuader_id', 'donation_ee', 'donation_er', 'extrovert', 'agreeable', 'conscientious', 'neurotic', 'open', 'age', 'income', 'sex', 'race', 'marital', 'employment', 'edu', 'religion', 'ideology']

,persuader_id,donation_ee,donation_er,extrovert,agreeable,conscientious,neurotic,open,age,income,sex,race,marital,employment,edu,religion,ideology
0,A03172343NB8PHOPICC1,0.0,0.05,3.8,4.0,3.8,2.4,4.6,22.0,6.0,Male,White,Unmarried,Employed for wages,Four-year college,Other religion,Conservative
1,A08663392NYK5WHK2M2M8,0.0,0.00,1.2,1.2,4.4,2.8,3.0,34.0,8.0,Male,White,Married,Employed for wages,Less than four-year college,Other religion,Conservative
2,A10249252O9I20MRSOBVF,0.0,0.00,3.0,4.2,4.8,1.0,3.4,54.0,6.0,Female,White,Married,Employed for wages,Less than four-year college,Catholic,Liberal
3,A10ARSSXF5SFCW,0.0,1.00,3.8,4.4,4.6,1.2,4.2,27.0,5.0,Female,Other,Married,Employed for wages,Less than four-year college,Protestant,Liberal
4,A10F0CHSNURXF5,0.1,0.05,5.0,4.6,4.8,1.2,4.8,46.0,12.0,Female,White,Married,Employed for wages,Four-year college,Catholic,Conservative

In [5]:
# drop any rows that do not contain a value in the bfp traits
df_persuaders = df_persuaders.dropna(subset=["extrovert", "agreeable", "conscientious", "neurotic", "open"])
# Add binary donated column
df_persuaders["donated"] = (df_persuaders["donation_ee"] > 0).astype(int)

print(df_persuaders.shape)
print(df_persuaders["donated"].value_counts())

(699, 18)
donated
1    411
0    288
Name: count, dtype: int64

In [6]:
#dataframe to csv
df_persuaders.to_csv("persuasion_for_good_clean.csv", encoding='utf-8', index=False)

In [7]:
#download CSV to work in Jamovi
from google.colab import files
files.download("persuasion_for_good_clean.csv")